# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\"\x1e\n\x0fGetStockRequest\x12\x0b\n\x03sku\x18\x01 \x01(\t\"$\n\x14\x42\x61tchGetStockRequest\x12\x0c\n\x04skus\x18\x01 \x03(\t\"^\n\tStockInfo\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x1a\n\x12quantity_available\x18\x02 \x01(\x05\x12\x16\n\x0eunit_price_eur\x18\x03 \x01(\x01\x12\x10\n\x08in_stock\x18\x04 \x01(\x08\"5\n\x0e\x42\x61tchStockInfo\x12#\n\x05items\x18\x01 \x03(\x0b\x32\x14.inventory.StockInfo\"4\n\x13ReserveStockRequest\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"T\n\x14ReserveStockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1a\n\x12remaining_quantity\x18\x03 \x01(\x05\"\x14\n\x12HealthCheckRequest\"%\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xbc\x02\n\x10InventoryService\x12<\n\x08GetStock\x12\x1a.inventory.GetStockRequest\x1a\x14.inventory.StockInfo\x12K\n\rBatchGetStock\x12\x1f.inventory.BatchGetStockRequest\x1a\x19.inventory.BatchStockInfo\x12O\n\x0cReserveStock\x12\x1e.inventory.ReserveStockRequest\x1a\x1f.inventory.ReserveStockResponse\x12L\n\x0bHealthCheck\x12\x1d.inventory.HealthCheckRequest\x1a\x1e.inventory.HealthCheckResponseB/Z-tutti-frutti/inventory-service/internal/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z-tutti-frutti/inventory-service/internal/proto'
  _globals['_GETSTOCKREQUEST']._serialized_start=30
  _globals['_GETSTOCKREQUEST']._serialized_end=60
  _globals['_BATCHGETSTOCKREQUEST']._serialized_start=62
  _globals['_BATCHGETSTOCKREQUEST']._serialized_end=98
  _globals['_STOCKINFO']._serialized_start=100
  _globals['_STOCKINFO']._serialized_end=194
  _globals['_BATCHSTOCKINFO']._serialized_start=196
  _globals['_BATCHSTOCKINFO']._serialized_end=249
  _globals['_RESERVESTOCKREQUEST']._serialized_start=251
  _globals['_RESERVESTOCKREQUEST']._serialized_end=303
  _globals['_RESERVESTOCKRESPONSE']._serialized_start=305
  _globals['_RESERVESTOCKRESPONSE']._serialized_end=389
  _globals['_HEALTHCHECKREQUEST']._serialized_start=391
  _globals['_HEALTHCHECKREQUEST']._serialized_end=411
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=413
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=450
  _globals['_INVENTORYSERVICE']._serialized_start=453
  _globals['_INVENTORYSERVICE']._serialized_end=769
# @@protoc_insertion_point(module_scope)
