# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import inventory_pb2 as inventory__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in inventory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InventoryServiceStub(object):
    """InventoryService is an internal-only gRPC service.
    It is never exposed directly to the UI; the gateway (or orders-service)
    talks to it over gRPC to check stock and fetch current pricing.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStock = channel.unary_unary(
                '/inventory.InventoryService/GetStock',
                request_serializer=inventory__pb2.GetStockRequest.SerializeToString,
                response_deserializer=inventory__pb2.StockInfo.FromString,
                _registered_method=True)
        self.BatchGetStock = channel.unary_unary(
                '/inventory.InventoryService/BatchGetStock',
                request_serializer=inventory__pb2.BatchGetStockRequest.SerializeToString,
                response_deserializer=inventory__pb2.BatchStockInfo.FromString,
                _registered_method=True)
        self.ReserveStock = channel.unary_unary(
                '/inventory.InventoryService/ReserveStock',
                request_serializer=inventory__pb2.ReserveStockRequest.SerializeToString,
                response_deserializer=inventory__pb2.ReserveStockResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/inventory.InventoryService/HealthCheck',
                request_serializer=inventory__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=inventory__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class InventoryServiceServicer(object):
    """InventoryService is an internal-only gRPC service.
    It is never exposed directly to the UI; the gateway (or orders-service)
    talks to it over gRPC to check stock and fetch current pricing.
    """

    def GetStock(self, request, context):
        """GetStock returns current stock level and unit price for a single fruit SKU.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchGetStock(self, request, context):
        """BatchGetStock returns stock info for multiple SKUs in one round trip.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReserveStock(self, request, context):
        """ReserveStock decrements stock when an order is placed (best-effort, in-memory demo).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """HealthCheck is a trivial RPC used by tests and CI to confirm the service is up.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStock': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStock,
                    request_deserializer=inventory__pb2.GetStockRequest.FromString,
                    response_serializer=inventory__pb2.StockInfo.SerializeToString,
            ),
            'BatchGetStock': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchGetStock,
                    request_deserializer=inventory__pb2.BatchGetStockRequest.FromString,
                    response_serializer=inventory__pb2.BatchStockInfo.SerializeToString,
            ),
            'ReserveStock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveStock,
                    request_deserializer=inventory__pb2.ReserveStockRequest.FromString,
                    response_serializer=inventory__pb2.ReserveStockResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=inventory__pb2.HealthCheckRequest.FromString,
                    response_serializer=inventory__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventory.InventoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inventory.InventoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InventoryService(object):
    """InventoryService is an internal-only gRPC service.
    It is never exposed directly to the UI; the gateway (or orders-service)
    talks to it over gRPC to check stock and fetch current pricing.
    """

    @staticmethod
    def GetStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/GetStock',
            inventory__pb2.GetStockRequest.SerializeToString,
            inventory__pb2.StockInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchGetStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/BatchGetStock',
            inventory__pb2.BatchGetStockRequest.SerializeToString,
            inventory__pb2.BatchStockInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReserveStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/ReserveStock',
            inventory__pb2.ReserveStockRequest.SerializeToString,
            inventory__pb2.ReserveStockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/HealthCheck',
            inventory__pb2.HealthCheckRequest.SerializeToString,
            inventory__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
